{{- if and (not .Values.existingSecret) (or .Values.settings.unifi.auth.user .Values.settings.unifi.auth.pass) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "unpoller.fullname" . }}
  labels:
    {{- include "unpoller.labels" . | nindent 4 }}
type: Opaque
stringData:
  UP_UNIFI_CONTROLLER_0_USER: {{ .Values.settings.unifi.auth.user | quote }}
  UP_UNIFI_CONTROLLER_0_PASS: {{ .Values.settings.unifi.auth.pass | quote }}
  {{- if .Values.settings.influxdb.enabled }}
  UP_INFLUXDB_USER: {{ .Values.settings.influxdb.auth.user | quote }}
  UP_INFLUXDB_PASS: {{ .Values.settings.influxdb.auth.pass | quote }}
  {{- with .Values.settings.influxdb.auth.auth_token }}
  UP_INFLUXDB_AUTH_TOKEN: {{ . | quote }}
  {{- end }}
  {{- end }}
{{- end }}
