{{- if eq (include "unpoller.renderSecret" .) "true" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "unpoller.fullname" . }}
  labels:
    {{- include "unpoller.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if or .Values.settings.unifi.auth.user .Values.settings.unifi.auth.pass }}
  UP_UNIFI_CONTROLLER_0_USER: {{ .Values.settings.unifi.auth.user | quote }}
  UP_UNIFI_CONTROLLER_0_PASS: {{ .Values.settings.unifi.auth.pass | quote }}
  {{- end }}
  {{- if .Values.settings.influxdb.enabled }}
  {{- if .Values.settings.influxdb.auth.auth_token }}
  UP_INFLUXDB_AUTH_TOKEN: {{ .Values.settings.influxdb.auth.auth_token | quote }}
  {{- else }}
  UP_INFLUXDB_USER: {{ .Values.settings.influxdb.auth.user | quote }}
  UP_INFLUXDB_PASS: {{ .Values.settings.influxdb.auth.pass | quote }}
  {{- end }}
  {{- end }}
{{- end }}
