{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "unpoller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "unpoller.fullname" . }}
    {{- with .Values.serviceMonitor.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "unpoller.labels" . | nindent 6 }}
  endpoints:
  - port: {{ .Values.service.name }}
{{- end }}