apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bookstack.fullname" . }}
  labels:
    {{- include "bookstack.labels" . | nindent 4 }}
spec:
  replicas: 1
  {{- with .Values.updateStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bookstack.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bookstack.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bookstack.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
        {{- if not .Values.existingSecret }}
          - name: DB_USER
            value: {{ .Values.config.dbUser | quote}}
          - name: DB_PASS
            value: {{ .Values.config.dbPass | quote}}
        {{- end }}
        {{- if .Values.config.dbHost }}
          - name: DB_HOST
            value: {{ .Values.config.dbHost | quote }}
        {{- else }}
          # this is mainly used for chart-testing and will use dynamically created DB_HOST string if not supplied from configuration
          # Uses chart release namespace to create a dbHost variable that works with embedded mariadb instance
          # Since chart-testing namespaces are randomly generated, this helps
          - name: DB_HOST
            value: {{ include "bookstack.defaultDatabaseHost" . }}
        {{- end }}
          - name: DB_PORT
            value: {{ .Values.config.dbPort | quote }}
          - name: DB_DATABASE
            value: {{ .Values.config.dbDatabase | quote }}
          - name: CACHE_DRIVER
            value: {{ .Values.config.cacheDriver | quote }}
          - name: SESSION_DRIVER
            value: {{ .Values.config.sessionDriver | quote }}
        {{- range $key, $val := .Values.extraEnv }}
          - name: {{ $key | upper }}
            value: {{ $val | quote }}
        {{- end }}
        {{- if .Values.existingSecret }}
          envFrom:
          - secretRef:
              name: {{ .Values.existingSecret }}
        {{- end }}
          ports:
            - name: "{{ .Values.service.name }}"
              containerPort: {{ .Values.service.port }}
              protocol: TCP
        {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
        {{- end }}
        {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
        {{- end }}
        {{- if .Values.startupProbe }}
          startupProbe:
            {{- toYaml .Values.startupProbe | nindent 12 }}
        {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
  {{- if .Values.persistence.existingClaim }}
        - name: config
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim  }}
  {{- else if .Values.persistence.enabled }}
        - name: config
          persistentVolumeClaim:
            claimName: {{ include "bookstack.fullname" . }}
  {{- else }}
        - name: config
          emptyDir: {}
  {{- end }}