{{- if not .Values.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bookstack.fullname" . }}
  labels:
    {{- include "bookstack.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USERNAME: {{ include "bookstack.dbUser" . | quote }}
  DB_PASSWORD: {{ include "bookstack.dbPassword" . | quote }}
  APP_KEY: {{ include "bookstack.appKey" . | quote }}
{{- end }}
