{{- if not .Values.settings.auth.existingSecret -}}
{{- with (.Values.settings.auth.token | default .Values.settings.auth.password) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pihole-exporter.fullname" $ }}
  labels:
    {{- include "pihole-exporter.labels" $ | nindent 4 }}
type: Opaque
stringData:
  PIHOLE_PASSWORD: {{ . | quote }}
{{- end }}
{{- end }}
