{{- range $key, $val := .Values.apps }}
{{- if $val.enabled }}
{{- $appName := printf "%s-%s" (include "exportarr.fullname" $) $key }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "exportarr.labels" $ | nindent 4 }}
    {{- range $key_label, $value_label := $.Values.metrics.serviceMonitor.additionalLabels }}
    {{ $key_label }}: {{ $value_label | quote }}
    {{- end }}
    app.kubernetes.io/component: {{ $appName }}
  name: {{ $appName }}
spec:
  endpoints:
  - interval: {{ $.Values.metrics.serviceMonitor.interval }}
    path: {{ $.Values.metrics.serviceMonitor.path }}
    port: {{ $.Values.service.name }}
    scrapeTimeout: {{ $.Values.metrics.serviceMonitor.scrapeTimeout }}
{{- if $.Values.metrics.serviceMonitor.relabelings }}
    relabelings:
      {{- toYaml $.Values.metrics.serviceMonitor.relabelings | nindent 6 }}
{{- end }}
{{- if $.Values.metrics.serviceMonitor.metricRelabelings }}
    metricRelabelings:
      {{- toYaml $.Values.metrics.serviceMonitor.metricRelabelings | nindent 6 }}
{{- end }}
  namespaceSelector:
    matchNames:
    - {{ $.Release.Namespace }}
  selector:
    matchLabels:
      {{- include "exportarr.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $appName }}
{{- if $.Values.metrics.serviceMonitor.targetLabels }}
  targetLabels:
{{- range $.Values.metrics.serviceMonitor.targetLabels }}
    - {{ . }}
{{- end }}
{{- end }}
---
{{- end }}
{{- end }}