---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "v-rising.fullname" . }}
  labels:
    {{- include "v-rising.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.server.type }}
{{- if eq .Values.service.server.type "LoadBalancer" }}
  {{- if .Values.service.server.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.server.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.server.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{ toYaml .Values.service.server.loadBalancerSourceRanges | indent 4 }}
  {{- end }}
{{- end }}
{{- if .Values.service.server.clusterIP }}
  clusterIP: {{ .Values.service.server.clusterIP }}
{{- end }}
{{- if .Values.service.server.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.server.externalTrafficPolicy }}
{{- end }}
  ports:
    - port: {{ .Values.service.server.gamePort.port }}
    {{- if .Values.service.server.gamePort.nodePort }}
      nodePort: {{ .Values.service.server.gamePort.nodePort }}
    {{- end }}
      targetPort: {{ .Values.service.server.gamePort.port }}
      protocol: UDP
      name: gameport
    - port: {{ .Values.service.server.queryPort.port }}
    {{- if .Values.service.server.queryPort.nodePort }}
      nodePort: {{ .Values.service.server.queryPort.nodePort }}
    {{- end }}
      targetPort: {{ .Values.service.server.queryPort.port }}
      protocol: UDP
      name: queryport
  {{- if .Values.service.server.externalIPs }}
  externalIPs:
    {{- with .Values.service.server.externalIPs }}
      {{- range . }}
        - {{ . | quote }}
      {{- end }}
    {{- end }}
  {{- end }}
  selector:
    {{- include "v-rising.selectorLabels" . | nindent 4 }}
