{{- if and (.Values.persistence.steamServer.enabled) (not .Values.persistence.steamServer.existingClaim) }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "v-rising.fullname" . }}-steam-server-files
  namespace: {{ .Release.Namespace }}
  {{- with .Values.persistence.steamServer.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "v-rising.labels" . | nindent 4 }}
spec:
  accessModes:
  {{- range .Values.persistence.steamServer.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.steamServer.size | quote }}
{{- if (eq "-" .Values.persistence.steamServer.storageClass) }}
  storageClassName: ""
{{- else if .Values.persistence.steamServer.storageClass }}
  storageClassName: "{{ .Values.persistence.steamServer.storageClass }}"
{{- end }}
  {{- with .Values.persistence.steamServer.selector }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}