{{- if and (.Values.persistence.world.enabled) (not .Values.persistence.world.existingClaim) }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "v-rising.fullname" . }}-world-files
  namespace: {{ .Release.Namespace }}
  {{- with .Values.persistence.world.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "v-rising.labels" . | nindent 4 }}
spec:
  accessModes:
  {{- range .Values.persistence.world.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.world.size | quote }}
{{- if (eq "-" .Values.persistence.world.storageClass) }}
  storageClassName: ""
{{- else if .Values.persistence.world.storageClass }}
  storageClassName: "{{ .Values.persistence.world.storageClass }}"
{{- end }}
  {{- with .Values.persistence.world.selector }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
