{{- if .Values.persistence.enabled }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "bookstack-file-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
  {{- if .Values.persistence.annotations }}
    {{ toYaml .Values.persistence.annotations | indent 2 }}  
  {{ end }}
  labels:
    {{- include "bookstack-file-exporter.labels" . | nindent 4 }}
spec:
  accessModes:
  {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: {{ .Values.persistence.storageClass }}
{{- end }}
  {{- if .Values.persistence.selector }}
  selector:
    {{ toYaml .Values.persistence.selector | indent 4 }}
  {{- end }}
{{- end }}