{{- if and (not .Values.existingSecret.name) (or .Values.auth.tokenId .Values.auth.tokenSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bookstack-file-exporter.fullname" . }}
  labels:
    {{- include "bookstack-file-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  BOOKSTACK_TOKEN_ID: {{ .Values.auth.tokenId | quote }}
  BOOKSTACK_TOKEN_SECRET: {{ .Values.auth.tokenSecret | quote }}
{{- end }}
