apiVersion: v2
name: exportarr
description: A Helm Chart to export Prometheus metrics for Arr applications.

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 2.0.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "v2.0.1"

# optional: include qbittorrent-exporter for prometheus
# ref: https://github.com/homeylab/helm-charts/tree/main/charts/qbittorrent-exporter
dependencies:
- name: qbittorrent-exporter
  version: "0.1.0"
  condition: qbittorrent-exporter.enabled
  repository: "oci://registry-1.docker.io/homeylabcharts"
- name: tdarr-exporter
  version: "1.1.7"
  condition: tdarr-exporter.enabled
  repository: "oci://registry-1.docker.io/homeylabcharts"