{{- if and (not .Values.settings.config.existingSecret.name) .Values.settings.config.apiKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tdarr-exporter.fullname" . }}
  labels:
    {{- include "tdarr-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  TDARR_API_KEY: {{ .Values.settings.config.apiKey | quote }}
{{- end }}
