apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qbittorrent-exporter.fullname" . }}
  labels:
    {{- include "qbittorrent-exporter.labels" . | nindent 4 }}
spec:
  replicas: 1
  {{- with .Values.updateStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "qbittorrent-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- if and (.Values.metrics.enabled) (not .Values.metrics.serviceMonitor.enabled) }}
      {{- with .Values.metrics.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
      labels:
        {{- include "qbittorrent-exporter.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "qbittorrent-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.service.name }}
              containerPort: {{ .Values.service.port }}
              protocol: {{ .Values.service.protocol }}
          env:
            - name: EXPORTER_PORT
              value: {{ .Values.service.port | quote }}
            - name: QBITTORRENT_HOST
              value: {{ .Values.settings.config.host | quote }}
            - name: QBITTORRENT_PORT
              value: {{ .Values.settings.config.port | quote }}
            - name: QBITTORRENT_SSL
              value: {{ .Values.settings.config.ssl | quote }}
          {{- with .Values.settings.config.urlBase }}
            - name: QBITTORRENT_URL_BASE
              value: {{ . | quote }}
          {{- end }}
            - name: VERIFY_WEBUI_CERTIFICATE
              value: {{ .Values.settings.config.verifyCert | quote }}
            - name: EXPORTER_LOG_LEVEL
              value: {{ .Values.settings.config.logLevel | quote }}
          {{- range $key, $val := .Values.extraEnv }}
            - name: {{ $key | upper }}
              value: {{ $val | quote }}
          {{- end }}
          {{- $managedSecret := and (not .Values.settings.auth.existingSecret) (or .Values.settings.auth.user .Values.settings.auth.pass .Values.settings.auth.apiKey) }}
          {{- if or .Values.settings.auth.existingSecret $managedSecret }}
          envFrom:
            - secretRef:
                name: {{ .Values.settings.auth.existingSecret | default (include "qbittorrent-exporter.fullname" .) }}
          {{- end }}
        {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
        {{- end }}
        {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
        {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
