{{- if not .Values.settings.auth.existingSecret -}}
{{- if or .Values.settings.auth.username .Values.settings.auth.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qbittorrent-exporter.fullname" . }}
  labels:
    {{- include "qbittorrent-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.settings.auth.username }}
  QBITTORRENT_USERNAME: {{ . | quote }}
  {{- end }}
  {{- with .Values.settings.auth.password }}
  QBITTORRENT_PASSWORD: {{ . | quote }}
  {{- end }}
{{- end }}
{{- end }}
