apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nut-exporter.fullname" . }}
  labels:
    {{- include "nut-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nut-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- if and (.Values.metrics.enabled) (not .Values.metrics.serviceMonitor.enabled) }}
      {{- with .Values.metrics.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
      labels:
        {{- include "nut-exporter.labels" . | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nut-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if or .Values.extraRunFlags .Values.webconfig_file }}
          args:
          {{- range $key, $val := .Values.extraRunFlags }}
            {{- if $val }}
            - --{{ $key }}={{ $val }}
            {{- else }}
            - --{{ $key }}
            {{- end }}
          {{- end }}
          {{- if .Values.webconfig_file}}
            - --web.config.file=/webconfig.yml
          {{- end }}
        {{- end }}
          env:
        {{- if not .Values.existingSecret }}
          {{- range $key, $val := .Values.settings.auth }}
          - name: {{ $key | upper }}
            value: {{ $val | quote }}
          {{- end }}
        {{- end }}
        {{- range $key, $val := .Values.settings.config }}
          - name: {{ $key | upper }}
            value: {{ $val | quote }}
        {{- end }}
        {{- range $key, $val := .Values.extraEnv }}
          - name: {{ $key | upper }}
            value: {{ $val | quote }}
        {{- end }}
          ports:
            - name: {{ .Values.service.name }}
              containerPort: {{ .Values.service.port }}
              protocol: {{ .Values.service.protocol }}
          ## to be implemented
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.webconfig_file }}
          - mountPath: /webconfig.yml
            name: webconfig
            subPath: webconfig.yml
          {{- end }}
      volumes:
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.webconfig_file }}
      - name: webconfig
        configMap:
          name: {{ include "nut-exporter.fullname" . }}-webconfig
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
