{{- if .Values.metrics.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "nut-exporter.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.metrics.serviceMonitor.additionalLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  name: {{ include "nut-exporter.fullname" . }}
spec:
  endpoints:
  - interval: {{ .Values.metrics.serviceMonitor.interval }}
    path: {{ .Values.metrics.serviceMonitor.path }}
    port: {{ .Values.service.name }}
    scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
{{- if .Values.metrics.serviceMonitor.relabelings }}
    relabelings:
{{ toYaml .ValuesserviceMonitor.relabelings | indent 4 }}
{{- end }}
{{- if .Values.metrics.serviceMonitor.metricRelabelings }}
    metricRelabelings:
{{ toYaml .Values.metrics.serviceMonitor.metricRelabelings | indent 4 }}
{{- end }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "nut-exporter.selectorLabels" . | nindent 8 }}
{{- if .Values.metrics.serviceMonitor.targetLabels }}
  targetLabels:
{{- range .Values.metrics.serviceMonitor.targetLabels }}
    - {{ . }}
{{- end }}
{{- end }}
{{- end }}