{{- range $instance_key, $instance_val := .Values.exportarr.apps }}
{{- range $app := $instance_val }}
{{- if $app.enabled }}

{{- $appMetrics := $.Values.exportarr.metrics -}}

{{- if $app.metrics }}
{{- $appMetrics = $app.metrics -}}
{{- end }}

{{- $appName := printf "%s-%s-%s" (include "exportarr.fullname" $) $instance_key $app.name }}
apiVersion: apps/v1
kind: Deployment
metadata:
  # $ = global scope, . = current scope
  name: {{ $appName }}
  labels:
    {{- include "exportarr.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $appName }}
spec:
  replicas: 1
  {{- with $.Values.exportarr.updateStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "exportarr.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $appName }}
  template:
    metadata:
      annotations:
      {{- with $.Values.exportarr.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- if and ($appMetrics.enabled) (not $appMetrics.serviceMonitor.enabled) }}
      {{- with $appMetrics.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
      labels:
        {{- include "exportarr.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/component: {{ $appName }}
    spec:
      {{- with $.Values.exportarr.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: "{{ include "exportarr.serviceAccountName" $ }}"
      securityContext:
        {{- toYaml $.Values.exportarr.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $appName }}
          securityContext:
            {{- toYaml $.Values.exportarr.securityContext | nindent 12 }}
          image: "{{ $.Values.exportarr.image.repository }}/{{ $.Values.exportarr.image.name }}:{{ $.Values.exportarr.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.exportarr.image.pullPolicy }}
          ports:
            - name: {{ $.Values.exportarr.service.name }}
              containerPort: {{ $.Values.exportarr.service.port }}
              protocol: {{ $.Values.exportarr.service.protocol }}
          args:
            - {{ $instance_key }}
          env:
            - name: URL
              value: {{ $app.url | quote }}
            {{- if $app.existingSecret.name }}
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ $app.existingSecret.name  }}
                  key: {{ $app.existingSecret.secretKey }}
            {{- else if $app.apiKey }}
            - name: API_KEY
              value: {{ $app.apiKey | quote }}
            {{- end }}
          {{- range $key_extra, $val_extra := $app.extraEnv }}
            - name: {{ $key_extra | upper }}
              value: {{ $val_extra | quote }}
          {{- end }}
          {{- range $key_chart, $val_chart := $.Values.exportarr.extraEnv }}
            - name: {{ $key_chart | upper }}
              value: {{ $val_chart | quote }}
          {{- end }}
        {{- if $.Values.exportarr.livenessProbe }}
          livenessProbe:
            {{- toYaml $.Values.exportarr.livenessProbe | nindent 12 }}
        {{- end }}
        {{- if $.Values.exportarr.readinessProbe }}
          readinessProbe:
            {{- toYaml $.Values.exportarr.readinessProbe | nindent 12 }}
        {{- end }}
        {{- if $.Values.exportarr.startupProbe }}
          startupProbe:
            {{- toYaml $.Values.exportarr.startupProbe | nindent 12 }}
        {{- end }}
          resources:
            {{- toYaml $.Values.exportarr.resources | nindent 12 }}
          volumeMounts:
          {{- with $.Values.exportarr.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $app.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
      {{- with $.Values.exportarr.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $app.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.exportarr.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.exportarr.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.exportarr.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- end }}
{{- end }}
{{- end }}