{{- range $instance_key, $instance_val := .Values.exportarr.apps }}
{{- range $app := $instance_val }}
{{- if $app.enabled }}
{{- $appName := printf "%s-%s-%s" (include "exportarr.fullname" $) $instance_key $app.name }}
{{- if and ($app.apiKey) (not (and ($app.existingSecret) ($app.existingSecret.name))) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $appName }}
  labels:
    {{- include "exportarr.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $appName }}
type: Opaque
stringData:
  API_KEY: {{ $app.apiKey | quote }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
