{{- if (.Values.exportarr.metrics.enabled) }}
{{- range $instance_key, $instance_val := .Values.exportarr.apps }}
{{- range $app := $instance_val }}

{{- $appMetrics := $.Values.exportarr.metrics -}}

{{- if $app.metrics }}
{{- $appMetrics = $app.metrics -}}
{{- end }}

{{- if and ($app.enabled) ($appMetrics.serviceMonitor.enabled) }}
{{- $appName := printf "%s-%s-%s" (include "exportarr.fullname" $) $instance_key $app.name }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "exportarr.labels" $ | nindent 4 }}
    {{- range $key_label, $value_label := $appMetrics.serviceMonitor.additionalLabels }}
    {{ $key_label }}: {{ $value_label | quote }}
    {{- end }}
    app.kubernetes.io/component: {{ $appName }}
  name: {{ $appName }}
spec:
  endpoints:
  - interval: {{ $appMetrics.serviceMonitor.interval }}
    path: {{ $appMetrics.serviceMonitor.path }}
    port: {{ $.Values.exportarr.service.name }}
    scrapeTimeout: {{ $appMetrics.serviceMonitor.scrapeTimeout }}
{{- if $appMetrics.serviceMonitor.relabelings }}
    relabelings:
      {{- toYaml $appMetrics.serviceMonitor.relabelings | nindent 6 }}
{{- end }}
{{- if $appMetrics.serviceMonitor.metricRelabelings }}
    metricRelabelings:
      {{- toYaml $appMetrics.serviceMonitor.metricRelabelings | nindent 6 }}
{{- end }}
  namespaceSelector:
    matchNames:
    - {{ $.Release.Namespace }}
  selector:
    matchLabels:
      {{- include "exportarr.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $appName }}
{{- if $appMetrics.serviceMonitor.targetLabels }}
  targetLabels:
{{- range $appMetrics.serviceMonitor.targetLabels }}
    - {{ . }}
{{- end }}
{{- end }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
