{{- range $instance_key, $instance_val := .Values.exportarr.apps }}
{{- range $app := $instance_val }}
{{- if $app.enabled }}
{{- $appName := printf "%s-%s-%s" (include "exportarr.fullname" $) $instance_key $app.name }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $appName }}
  labels:
    {{- include "exportarr.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $appName }}
spec:
  type: {{ $.Values.exportarr.service.type }}
  ports:
    - port: {{ $.Values.exportarr.service.port }}
      targetPort: {{ $.Values.exportarr.service.port }}
      protocol: {{ $.Values.exportarr.service.protocol }}
      name: {{ $.Values.exportarr.service.name }}
  selector:
    {{- include "exportarr.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $appName }}
---
{{- end }}
{{- end }}
{{- end }}