{{- range $instance_key, $instance_val := .Values.exportarr.apps }}
{{- range $app := $instance_val }}

{{- $metricsEnabled := $.Values.exportarr.metrics.enabled -}}
{{- $smConfig := $.Values.exportarr.metrics.serviceMonitor -}}
{{- $smEnabled := $.Values.exportarr.metrics.serviceMonitor.enabled -}}

{{- if $app.enabled }}

{{- if $app.metrics }}

{{- if and ($metricsEnabled) ($app.metrics.serviceMonitor) }}
{{- $smConfig = $app.serviceMonitor -}}
{{- if hasKey $app.metrics.serviceMonitor "enabled" }}
{{- $smEnabled = $app.metrics.serviceMonitor.enabled -}}
{{- end }}
{{- end }}

{{- end }}

{{- if and ($metricsEnabled) ($smEnabled) }}
{{- $appName := printf "%s-%s-%s" (include "exportarr.fullname" $) $instance_key $app.name }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "exportarr.labels" $ | nindent 4 }}
    {{- range $key_label, $value_label := $smConfig.additionalLabels }}
    {{ $key_label }}: {{ $value_label | quote }}
    {{- end }}
    app.kubernetes.io/component: {{ $appName }}
  name: {{ $appName }}
spec:
  endpoints:
  - interval: {{ $smConfig.interval }}
    path: {{ $smConfig.path }}
    port: {{ $.Values.exportarr.service.name }}
    scrapeTimeout: {{ $smConfig.scrapeTimeout }}
{{- if $smConfig.relabelings }}
    relabelings:
      {{- toYaml $smConfig.relabelings | nindent 6 }}
{{- end }}
{{- if $smConfig.metricRelabelings }}
    metricRelabelings:
      {{- toYaml $smConfig.metricRelabelings | nindent 6 }}
{{- end }}
  namespaceSelector:
    matchNames:
    - {{ $.Release.Namespace }}
  selector:
    matchLabels:
      {{- include "exportarr.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $appName }}
{{- if $smConfig.targetLabels }}
  targetLabels:
{{- range $smConfig.targetLabels }}
    - {{ . }}
{{- end }}
{{- end }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}