name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
        contents: write 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: true # https://github.com/helm/chart-releaser-action/issues/97
  oci:
    runs-on: ubuntu-latest
    environment: 'dockerhub' 
    steps:
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.1 # default is latest (stable)
        # id: install
      - name: Helm Registry Login
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | helm registry login registry-1.docker.io --password-stdin -u ${{ secrets.DOCKERHUB_USERNAME }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Helm Package Charts
        run: for x in $(ls charts); do make pkg app=${x}; done
      - name: Helm Push Charts
        run: for x in $(ls *.tgz); do make oci_push ${x}; done